### ISSUE TITLE
Buttons should have the same design

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#1]
The orange validation button has no radius
The grey cancel button has radius

![image](https://cloud.githubusercontent.com/assets/7809189/5994085/2e3894da-aa67-11e4-992a-04477250ae5d.png)

**Comment by RaviG76** [comment]
Done.

**Comment by jchout** [comment]
Some buttons / fields remain:

![image](https://cloud.githubusercontent.com/assets/7809189/6000556/8389de80-aadf-11e4-88df-40acda0d5435.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6000586/dad18b48-aadf-11e4-8d63-338c82c9ddad.png)

Can you add radius for all buttons and in place editable fields to provide the same design please?
