### ISSUE TITLE
In-place editing

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#12]
Add in-place editing here also:

![image](https://cloud.githubusercontent.com/assets/7809189/5994342/7e42fbe8-aa6f-11e4-923f-8bb0cf03e8b0.png)

**Comment by RaviG76** [comment]
Done.

**Comment by jchout** [comment]
Not good:
- vertical-align
- amount format : "1 234,56", not "$1,234.56"

![image](https://cloud.githubusercontent.com/assets/7809189/6000524/0ef91cf2-aadf-11e4-8a84-5a581edab46c.png)
