### ISSUE TITLE
1 item is missing in list

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#17]
In NAF code:
When typing 62.0 -> I get 62.01Z, 62.02A, 62.02B, 62.03Z
When typing 62.02 -> I get only 62.02A. 62.02B is missing

![image](https://cloud.githubusercontent.com/assets/7809189/6006007/48fd3ae8-ab0f-11e4-9863-09134746892c.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6006017/79eac08a-ab0f-11e4-98a8-abaf9c15ff2f.png)

**Comment by RaviG76** [comment]
Done.
