### ISSUE TITLE
Editable zone should have a width twice larger

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#2]
To allow large company name, street addresses, city etc...

![image](https://cloud.githubusercontent.com/assets/7809189/5994099/a06a5b7e-aa67-11e4-803d-9d1265d031c8.png)

![image](https://cloud.githubusercontent.com/assets/7809189/5994137/bee48880-aa68-11e4-9a01-07709c352d1e.png)

![image](https://cloud.githubusercontent.com/assets/7809189/5994223/44d53ef6-aa6b-11e4-8bd9-b7358bb5e6d0.png)

**Comment by RaviG76** [comment]
Done
