### ISSUE TITLE
Error in calculation

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#21]
With the following settings,

![image](https://cloud.githubusercontent.com/assets/7809189/6068248/fb209950-ad7a-11e4-950d-cedbfd584a51.png)

I got 1 error:

![image](https://cloud.githubusercontent.com/assets/7809189/6068182/81d0048c-ad7a-11e4-8b84-92f243ad44a3.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6068189/91dd89ee-ad7a-11e4-9944-78ea4ae13ccc.png)

And another one:

![image](https://cloud.githubusercontent.com/assets/7809189/6068218/ca946c30-ad7a-11e4-940f-b16518e61014.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6068206/bc30e93e-ad7a-11e4-8cb0-b697270b5b91.png)

**Comment by RaviG76** [comment]
Done.
