### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#22]
Wrong interspace (height):

![image](https://cloud.githubusercontent.com/assets/7809189/6068467/9a0e0d62-ad7c-11e4-800e-7e563d4f7bba.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6068458/8d8ab9a0-ad7c-11e4-9adc-d54c8e689b09.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6068478/b51e4d10-ad7c-11e4-865c-6a4caec23434.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6068491/cebf6f38-ad7c-11e4-807b-21545ff64446.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6068506/e7154eea-ad7c-11e4-9423-813af60f36ab.png)

**Comment by RaviG76** [comment]
Done.
