### ISSUE TITLE
Design: french format required

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#23]
Sal. Tp plein: "1 234,56"
% d'activité :"123,45 %"
Heures /Mois : "123,45"

![image](https://cloud.githubusercontent.com/assets/7809189/6068581/7ce28636-ad7d-11e4-94b9-467883f53572.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6116383/7c4722a4-b0ac-11e4-960d-80d89c1e533e.png)

**Comment by RaviG76** [comment]
Done.

**Comment by jchout** [comment]
Quite good, some fields remain:
![image](https://cloud.githubusercontent.com/assets/7809189/6130617/5a6e87d6-b146-11e4-81f6-6c3b02d8ad93.png)

and some fields are not right-aligned:
![image](https://cloud.githubusercontent.com/assets/7809189/6130629/72d4c100-b146-11e4-86cf-5d73359ae7cc.png)

**Comment by RaviG76** [comment]
Done.
