### ISSUE TITLE
Control field: SIREN code

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#25]
SIREN code: in case there is more or less 9 digits,
the message should be "Veuillez saisir 9 chiffres"

**Comment by RaviG76** [comment]
Done.

**Comment by jchout** [comment]
Letters must not be accepted for SIREN and Securite Sociale:

![image](https://cloud.githubusercontent.com/assets/7809189/6081595/264cbd48-ae1b-11e4-9f16-01a88a9c7b91.png)

**Comment by RaviG76** [comment]
Done.
