### ISSUE TITLE
Control field: No Securite Sociale

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#26]
If there is more or less than 15 digits, the message should be "Veuillez saisir 15 chiffres"
![image](https://cloud.githubusercontent.com/assets/7809189/6069055/8504a368-ad81-11e4-840f-cdb560bac3ba.png)

In addition, there is a bug: when i enter more than 15 digits, the field disapear:
![image](https://cloud.githubusercontent.com/assets/7809189/6069104/e59a23f6-ad81-11e4-9d20-6fb04617b2b3.png)
![image](https://cloud.githubusercontent.com/assets/7809189/6069108/f3655b22-ad81-11e4-9ba6-5e58d4ec97f0.png)

**Comment by RaviG76** [comment]
Done.

**Comment by jchout** [comment]
Not ok. Only digits should be accepted:

![image](https://cloud.githubusercontent.com/assets/7809189/6081606/43f60eb2-ae1b-11e4-8091-760542fe22a2.png)

**Comment by RaviG76** [comment]
Done.
