### ISSUE TITLE
Bug in date picker

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#27]
When i select a date:
![image](https://cloud.githubusercontent.com/assets/7809189/6069184/aa213660-ad82-11e4-8f74-d35ce4e06096.png)

The selection is not stored:
![image](https://cloud.githubusercontent.com/assets/7809189/6069191/bc23e3da-ad82-11e4-8bf7-f026e2d16232.png)

When i update this date:
![image](https://cloud.githubusercontent.com/assets/7809189/6069236/fa6543f0-ad82-11e4-89fb-9819093353f9.png)

these 2 dated are updated with the same date:
![image](https://cloud.githubusercontent.com/assets/7809189/6069240/0bbb8f60-ad83-11e4-9909-de6d89f9f289.png)

**Comment by RaviG76** [comment]
After selecting date from date picker you need to click on tick arrow button then it will store the date.
