### ISSUE TITLE
New (floating) form

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#30]
Calculation are described in Payroll 12d file:

![image](https://cloud.githubusercontent.com/assets/7809189/6070702/3e3bd4a2-ad8f-11e4-8d0b-e212f1a32ad8.png)

This should be a floating form like:
![image](https://cloud.githubusercontent.com/assets/7809189/6070819/08273626-ad90-11e4-9ba3-25fced6ffbe4.png)

Cf. http://www.keenthemes.com/preview/metronic/theme/templates/admin2/
(click the gear icon on top right)

**Comment by RaviG76** [comment]
Done
