### ISSUE TITLE
Design: old browsers

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#32]
For old browsers (ex: IE8), redirect to a page /update-your-browser like this one:

http://www.typeform.com/update-your-browser

**Comment by RaviG76** [comment]
I have added the restriction for following browsers:
IE Version < 9
Firefox <= 24
Chrome Version <= 29
Canary Version <= 32
Safari Version <= 5
Opera Version <= 16

**Comment by jchout** [comment]
Not ok: it shoud be a page "like" this one: http://www.typeform.com/update-your-browser
But the redirection should be /update-your-browser, not www.typeform.com/update-your-browser

I do not want users to be redirected to external web site.

In french:

/update-your-browser --> /mettez-a-jour-votre-navigateur
Woof! --> Oups!
It's time to update your browser. --> Il est temps de mettre à jour votre navigateur.
Just click on one of these browsers and enjoy Typeform. --> Cliquez sur l'un des icônes et profitez de MonBulletindePaie.com.

**Comment by RaviG76** [comment]
Done.
