### ISSUE TITLE
Issue: this value should be editable "in place"

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#34]
- with french format of course

![image](https://cloud.githubusercontent.com/assets/7809189/6114961/4a442090-b0a2-11e4-96ee-c43dc1d677b5.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6114968/5b17ec44-b0a2-11e4-9cc0-c7ac92aa0973.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6114977/6a39f406-b0a2-11e4-9fbe-70ff302762af.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6115955/a4046afc-b0a9-11e4-8b90-792d4cabbbe8.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6115975/c7628c86-b0a9-11e4-82b9-b76b6867cd37.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6116132/9b39f9e0-b0aa-11e4-9619-0d489f614545.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6115010/b2edec8e-b0a2-11e4-810f-d620ffebcc44.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6115016/bf21559a-b0a2-11e4-9d1b-ff034e11ae5d.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6115019/cb20e414-b0a2-11e4-8305-09bf44f003ea.png)

These values should be also editable "in place" + if Assurance Santé = "Rég. Gén.", then these values should be null (0,00):
![image](https://cloud.githubusercontent.com/assets/7809189/6114986/7b70e900-b0a2-11e4-86d0-cd54d1c9f9d1.png)
![image](https://cloud.githubusercontent.com/assets/7809189/6114989/85418692-b0a2-11e4-8a84-36eaf671aad5.png)

This value should be also editable "in place" + if Assurance Chomage = "Rég. Gén.", then this value should be null (0,00):
![image](https://cloud.githubusercontent.com/assets/7809189/6114996/93f4511a-b0a2-11e4-8e61-222b00583137.png)

This value should be also editable "in place" + if Assurance Retraite = "Rég. Gén.", then this value should be null (0,00):
![image](https://cloud.githubusercontent.com/assets/7809189/6115001/9cb3f4ea-b0a2-11e4-9f9e-d96f88e6847e.png)

**Comment by RaviG76** [comment]
I think this should be enhancement because previously I thought we only need to display values in popup   that is why I have not implemented in place editing for these values :)

**Comment by RaviG76** [comment]
Done.
