### ISSUE TITLE
Enhancement: this value should be editable "in place"

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#35]
In the row ATMP Cotisations Accidents du Travail / Maladie Professionnelle, this value should be editable "in place" (if null, then display "0,00 %"):
![image](https://cloud.githubusercontent.com/assets/7809189/6115069/22c4cc26-b0a3-11e4-9e81-1d1ffc56b48d.png)

In the row AM-C Mutuelle complémentaire, this value should be editable "in place"  (if null, then display "0,00 %"): 
![image](https://cloud.githubusercontent.com/assets/7809189/6115084/3ad1c2ce-b0a3-11e4-9d83-19d8dcbf0ba5.png)

In the row PR-C Prévoyance complémentaire, this value should be editable "in place"  (if null, then display "0,00 %"): 
![image](https://cloud.githubusercontent.com/assets/7809189/6115093/506e96fc-b0a3-11e4-8290-4ab91847d6b7.png)

And this value should be editable "in place" also (if null, then display "0,00 %"): 
![image](https://cloud.githubusercontent.com/assets/7809189/6115101/6b2f220e-b0a3-11e4-92ee-900aa87411c9.png)

**Comment by RaviG76** [comment]
Done.

**Comment by jchout** [comment]
not ok: these values:
![image](https://cloud.githubusercontent.com/assets/7809189/6131457/5c000dbc-b14c-11e4-916d-3f50f3678e98.png)

should have effect on that one:
![image](https://cloud.githubusercontent.com/assets/7809189/6131464/6c75c2c2-b14c-11e4-9f38-7faa5ebb5aea.png)

and of course any sums and calculations related to these cells

**Comment by RaviG76** [comment]
Done.
