### ISSUE TITLE
Issue: this value has no effect

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#38]
![image](https://cloud.githubusercontent.com/assets/7809189/6116238/6f37b23c-b0ab-11e4-9d0b-8878a99ae636.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6116247/8a3c5434-b0ab-11e4-89cf-e83b0e591bb5.png)

![image](https://cloud.githubusercontent.com/assets/7809189/6116257/96b797c8-b0ab-11e4-8074-aa659eb005a2.png)

**Comment by RaviG76** [comment]
Done.
