### ISSUE TITLE
In zip code / city, an empty list is displayed when selection is null or wrong

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#4]
![image](https://cloud.githubusercontent.com/assets/7809189/5994150/14ef19b6-aa69-11e4-86f1-6f3059889b85.png)

![image](https://cloud.githubusercontent.com/assets/7809189/5994151/20f09b54-aa69-11e4-8560-573089906305.png)

It's the same for NAF code:
![image](https://cloud.githubusercontent.com/assets/7809189/5994178/b6b09f36-aa69-11e4-95f8-0db5d42cfe09.png)

**Comment by RaviG76** [comment]
Done.
