### ISSUE TITLE
Error in design

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#41]
When this value is set to "Rég. Gén."
![image](https://cloud.githubusercontent.com/assets/7809189/6131204/977147d2-b14a-11e4-9dbd-ecec6e6b8fec.png)

These values should be set automatically to "0,00":
![image](https://cloud.githubusercontent.com/assets/7809189/6131214/a8c32352-b14a-11e4-9992-4dc571d516d3.png)

It's the same for:
![image](https://cloud.githubusercontent.com/assets/7809189/6131261/f6db9308-b14a-11e4-9100-4220524bdac8.png)
and:
![image](https://cloud.githubusercontent.com/assets/7809189/6131266/fff6b742-b14a-11e4-971d-b166234c05f5.png)

Pay attention to issue 42

**Comment by RaviG76** [comment]
Done.
