### ISSUE TITLE
Update text

### ISSUE THREAD

**Issue by jchout** [RaviG76/Payrollv2#9]
Replace by : "Veuillez patienter..."
![image](https://cloud.githubusercontent.com/assets/7809189/5994283/2098c132-aa6d-11e4-86b7-8f4e051fcb95.png)

Web page title: replace "Payroll App" by "Mon Bulletin de Paie"

Footer:replace by "Copyright (c) 2015 by <a href="www.mydigilife.com">MYDIGILIFE</a> - Tous Droits Réservés".
![image](https://cloud.githubusercontent.com/assets/7809189/5994289/634fda56-aa6d-11e4-9eea-248e31fd621b.png)

**Comment by RaviG76** [comment]
Done.
